import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin,AiFillGithub} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png'
import consulting from '../public/consult.png'
import {useState} from 'react';


export default function Home() {
  const [darkMode,setDarkMode]=useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Scinteie Stefan's Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px 10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>Developed by Stevenscn</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl' onClick={()=>setDarkMode(!darkMode)}/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' 
              href='#'
              >
              Resume</a></li>
            </ul>
          </nav>

        <div className='text-center p-10 '>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'>Stefan Scinteie</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200'>
          As a developer with a pragmatic approach and a passion for making a positive impact in the world, 
          I am constantly seeking opportunities to collaborate with talented individuals and tackle complex problems. 
          I am always eager to learn new things and push myself beyond my comfort zone to achieve my goals.
          </p>
        </div>
          
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600  dark:text-gray-400"'>
        <a href='https://www.linkedin.com/in/stefan-scinteie-51b88825b/' target={'_blank'}>
          <AiFillLinkedin></AiFillLinkedin>
        </a>
        <a href='https://github.com/SparkFlowGt' target={'_blank'}>
          <AiFillGithub />
        </a>
        </div>


        </section>

        <section>
          <div>
            <div>
            <h3 className='text-center text-3xl py-1 dark:text-white'>
              Skills
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 text-center'>
              HTML CSS JS <span className='text-teal-500'>test </span>
              
            </p>
            </div>
          </div>

          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1'>
              <Image alt="code" src={code} width={100} height = {100}/>
              <h4 className='py-4 text-teal-600'>Tehnologies I am curently improving</h4>
              <p className='text-gray-800 py-1'>HTML</p>
              <p className='text-gray-800 py-1'>CSS</p>
              <p className='text-gray-800 py-1'>JS</p>
              <p className='text-gray-800 py-1'>REACT</p>
            
            </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <h4 className='py-4 text-teal-600'>Tehnologies I am curently improving</h4>
              <p className='text-gray-800 py-1'>HTML</p>
              <p className='text-gray-800 py-1'>CSS</p>
              <p className='text-gray-800 py-1'>JS</p>
              <p className='text-gray-800 py-1'>REACT</p>
            
            </div>
            
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <h4 className='py-4 text-teal-600'>Tehnologies I am curently improving</h4>
              <p className='text-gray-800 py-1'>HTML</p>
              <p className='text-gray-800 py-1'>CSS</p>
              <p className='text-gray-800 py-1'>JS</p>
              <p className='text-gray-800 py-1'>REACT</p>
            
            </div>
          </div>
          
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>
              Portofolio
            </h3>
          </div>
        </section>
        
      </main>
    </div>
  )
}
